### PR TITLE
Present offline availability

### PR DESCRIPTION
**Pull request by md8n**
# Description

Demonstrates showing a given page's offline availability status in the `card` and also in the heading (for some).
Also fixes a logic bug.

### CODE REVIEW

**Comment by PeteCoward** [comment]
I'd like to leave this open for the demonstration, but not checkin the riot code parts of it, but sounds like you want the logic fix. Let's talk how to get around this

**Comment by PeteCoward** [comment]
It "works" but includes media assets in the description of available offline. Which may in fact be what we want :)

**Comment by md8n** [comment]
> I'd like to leave this open for the demonstration, but not checkin the riot code parts of it, but sounds like you want the logic fix. Let's talk how to get around this

I only found the logic problem of course by doing the riot stuff.  Maybe I'll do a little :pr: with that stuff in it, on its own.

**Comment by PeteCoward** [comment]
made this draft for now

**Comment by md8n** [comment]
Closed this, as the key outcome was finding the logic problem and the :pr: for that has already been merged.

**Pull request closed without merging**
