### PR TITLE
Front-end Social Learning

### PR DESCRIPTION
**Pull request by megganeturner**
### Updated Description:

This is ready to start reviewing I think!
Requires https://github.com/catalpainternational/canoe-backend/pull/160 for the backend (note this PR will need to be merged to resolve manifest issues too: https://github.com/catalpainternational/canoe-backend/pull/174)
Designs are here: https://projects.invisionapp.com/d/#/console/21265373/448758613/preview#project_console

Discussion questions are created in wagtail under _lessons_. Then click into the corresponding course to see & interact with the new discussion elements.

Addresses several issues:
-  #610 On a Course detail page, I can select to see Lessons or Discussion
- #611 Opening the discussion, I see a list of comments
- #612 On a discussion, I can add comments
- #654 As a user, I can flag comments as being inappropriate
- #613 I am informed whether my comment was successful or not
- #616 At the end of an activity, I am invited to participate in a discussion

Still todo:
- still awaiting designs for empty states / error states

There will undoubtedly be things I've missed in the COSs across these issues, but I'd love to get this initial chunk of work in before this PR becomes a monster

<hr>

### Old Description:

DRAFT so backend can check requirements

Designs are here: https://projects.invisionapp.com/d/#/console/21265373/448758613/preview#project_console

[In the UI](https://projects.invisionapp.com/d/#/console/21265373/448758614/preview#project_console), discussion questions for each lesson are available at the **course overview level**.

At [this](https://canoe-redesign.temp.build/api/v2/pages/106/?version=1617186395151467) level of the API, nested in each `lessons` object, the FE needs the following information:
- all discussion questions for each lesson
e.g:
<pre>
"lessons": [
        {
            "id": 109,
            "title": "Caring for Plants",
            "slug": "caring-for-plants",
            "description": "Learn how to care for plants",
            "long_description": "Plants need lots of love and attention. Learn how to care for your plants.",
            "translations": {
                "tet": 8,
                "pt": 9
            },
            "card_image_url": "/media/images/leaf.2e16d0ba.fill-320x160-c50.format-jpeg.jpg"
            <b>"discussion": [{
                "id": "a3e23d87-8a3b-48cb-9d2c-e0508176b51a",
                "question": "How do you feel about caring for plants?"
            }]</b>
        }
]
</pre>

[Clicking into a thread](https://projects.invisionapp.com/d/#/console/21265373/448758612/preview#project_console) displays the associated lesson title, the discussion question/topic, and all of the comments/replies for that question/topic.
Perhaps this should come through on [the endpoint for lessons](https://canoe-redesign.temp.build/api/v2/pages/109/?version=1617186395151467). Note [there is a PR ](https://github.com/catalpainternational/canoe-backend/pull/145) which adds a `discussion` array to this endpoint. Right now it only contains the `question` & `id` attributes, but could include the nested comments & replies too?
On this level we need:
- lesson title
- lesson id
- lesson question/thread/discussion
  - id
  - question
  - comments & replies?
- previously I mentioned we would need the lesson image here, but this is no longer necessary

Comments and replies need:
- id
- comment text
- user id
- user first name
- user last name
- timestamp
- a reference to any replies/parents - will depend on the shape of the data: (see thoughts/examples below)
  - if the comment is a top level comment: any replies
  - OR if the comment is a reply: the id of the comment it is in reply to 

For comments:
src/riot/Components/DiscussionThread.riot.html line 58 - describes the shape of data for getting comments
src/riot/Components/DiscussionThread.riot.html line 196 - describes the shape of data for posting comments

Questions here:
would it be better to have a flat or nested array for handling replies, e.g.
```
flat array:
[{
  id: 1,
  parentId: null,
  text: 'hello'
}, {
  id: 2,
  parentId: 1,
  text: 'hi!'
}]

OR:

nested array:
[{
  id: 1,
  text: 'hello',
  replies: [{
     id: 2,
     text: 'hi!'
  }]
}]
```

For the sake of mocking this data in, I've assumed a flat array, but this is easy enough to change (or if another format altogether is better that's fine too!)

### CODE REVIEW

**Comment by PeteCoward** [comment]
So to check my understanding...

A CoursePage shows ( when in the right tab ) a DiscussionCard for each DiscussionThread attached to the Lessons in the Course. 
When a user selects a Discussion by clicking on the Card, the Thread shows.
A Thread is a list of DiscussionComments, each of which can have a list of DiscussionReplies.

I think on the backend we'd just have a single model for a Post ( to avoid using Comment or Reply ), and just deliver the structure you want.

The Lesson.ts object would expose a `get threads() Thread<>;` member which would be synchronous delivered form the Page api data and just contatin the top level questions which have been added in wagtail.

The `Thread` js object would allow you to access a `get commentsPromise Promise<Comment>;` that would be asynchronous and read from the API ( or the cache ). Or fail if no network.
It will also expose an asyncronous `postComment(commentData): Promise<boolean>` you can call to post the comment to the server. Will fail if no network.

The `Comment` js object would give access to the fields you need, and contain a list of Reply js objects that would also have the data you needed.
It will also expose an asyncronous `postReply(replyData): Promise<boolean>` you can call to post the replay to the server. Will fail if no network.

**Comment by megganeturner** [comment]
@PeteCoward yepp, that understanding is correct! The model hierarchy is `Lesson` hasMany `Threads` hasMany `Comments` hasMany `Replies`

A single model for comment & reply makes sense to me. I've trying to make it so the front-end only needs one DiscussionComment component to reflect this, but riot is making it challenging. I'll keep hacking away!

That all looks good to me!

**Comment by PeteCoward** [comment]
> I've trying to make it so the front-end only needs one DiscussionComment component to reflect this

I don't think you need to!

**Comment by boerwastaken** [comment]
Why have separate concepts of threads and comments? If a comment is in-reply-to another comment, then it's part of a thread, if not, then not. It's an emergent property.

**Comment by PeteCoward** [comment]
> Why have separate concepts of threads and comments? If a comment is in-reply-to another comment, then it's part of a thread, if not, then not. It's an emergent property.

Are you asking about Meggan's code, or my comment?

**Comment by megganeturner** [comment]
> Why have separate concepts of threads and comments? If a comment is in-reply-to another comment, then it's part of a thread, if not, then not. It's an emergent property.

Good point @boerwastaken! , thread here is possibly not the best word. By thread in this logic we're talking about the _question_, or discussion topic for a given lesson. A thread is a question, which has comments/replies.

Designs for reference:


Screen Shot 2021-04-15 at 9 43 25 am

Screen Shot 2021-04-15 at 9 43 11 am

**Comment by boerwastaken** [comment]
Thanks! I see.
The second example features what I'd casually call a thread - Jerome replying to Jen, Jen replying to the question. Technically speaking I'd say every comment is a "thread" of 1 or more comments, or in other words, threads don't exist as a standalone concept - there's just comments, parented either by another comment or by the original question.

As often, the design doesn't show what happens when a "thread" lives 5 levels deep. Extrapolating from design number 2, there's just no space to indent that much!

Furthermore, people, especially casual or first-time users, don't understand threading very well and even if they do, they will not always do it consistently. Given that AND the design problems that threading impose (such as the indentation issue) I would argue to reconsider whether we really want and need "threads", but who am I ;-)

For a workable middle-ground pseudosolution, see Facebook's: messages have "reply" buttons, if the message you're replying to is a top-level (0-deep) comment, you'll be starting a thread (1-deep), if not, you'll be quoting the message and replying 1-deep, appending any other 1-deep comment.

Just my 2 centavos.

**Comment by PeteCoward** [comment]
> As often, the design doesn't show what happens when a "thread" lives 5 levels deep. Extrapolating from design number 2, there's just no space to indent that much!

This was discussed in design, and specified clearly, there will be no ability to dive down a rabbit hole of reply depth. 
Users can comment on questions, and reply to comments, do nothing on replies if you see what I mean.
Deliberate restriction due to screen space issues, we're not building a full forum here :)

**Comment by boerwastaken** [comment]
Great, that would avoid many troublesome aspects. Sorry, seeing a mockup flash by that doesn't indicate what happens to responses-to-responses sets of alarm bells in my head, especially if it's for mobile, and I had to ask!

**Comment by PeteCoward** [comment]
@megganeturner I'm getting a ```
DiscussionThread.riot.html?1d14:268 Uncaught (in promise) TypeError: Cannot set property 'className' of null
    at Object.commentStatus (DiscussionThread.riot.html?1d14:268)
    at eval (DiscussionThread.riot.html?1d14:290)
```
on flagging a comment as innapropriate

**Comment by megganeturner** [comment]
> @megganeturner I'm getting a
> 
> ```
> DiscussionThread.riot.html?1d14:268 Uncaught (in promise) TypeError: Cannot set property 'className' of null
>    at Object.commentStatus (DiscussionThread.riot.html?1d14:268)
>    at eval (DiscussionThread.riot.html?1d14:290)
> ```
> 
> on flagging a comment as innapropriate

Should be resolved now, thanks Peter!

**Comment by PeteCoward** [comment]
also on finishing a lesson we are getting
```
LessonComplete.riot.html?fab1:74 Uncaught (in promise) TypeError: Cannot read property 'threads' of undefined
    at Object.lessonHasDiscussion (LessonComplete.riot.html?fab1:74)
    at Object.evaluate (LessonComplete.riot.html?fab1:28)
    at Object.update (riot.esm.js?93b9:799)
    at Object.mount (riot.esm.js?93b9:795)
    at eval (riot.esm.js?93b9:1661)
    at Array.forEach (<anonymous>)
    at Object.mount (riot.esm.js?93b9:1661)
    at mount (riot.esm.js?93b9:807)
    at Object.update (riot.esm.js?93b9:812)
    at Object.mount (riot.esm.js?93b9:795)
```
I think you just need to remove `state.`

**Review by PeteCoward — APPROVED** [review]
Thanks Meggan, getting this up to jid-staging

**Pull request merged**
