### PR TITLE
Storage container page and asset

### PR DESCRIPTION
**Pull request by md8n**
# Description

This makes a set of little tweaks to get both `Page` and `Asset` to use the `Page`'s storage_location for their cache name (as originally intended).

It also corrects how `Page` and `Asset` are connected using the internal `Id` within the `Asset`.  And it allows for the `Asset`'s `Id` to be a `string` or a `number` in the original manifest data.

### CODE REVIEW

**Review by PeteCoward — COMMENTED** [review]
I'm seeing this make a weird request to `/media/` which causes a console error, not sure why it does that

**Comment by md8n** [comment]
> I'm seeing this make a weird request to `/media/` which causes a console error, not sure why it does that

That occurs because it can't figure out the rendition for that asset correctly.  Have you got your canoe-backend updated properly?

**Comment by md8n** [comment]
Can you make sure you have the very latest pull for this :pr: - I can't repeat that problem now, which was fixed with my second commit to this branch

**Comment by PeteCoward** [comment]
Thanks @md8n I might have been running a commit behind.
See #405 for a fix for this when logged out

**Review by PeteCoward — APPROVED** [review]

**Pull request merged**
