### PR TITLE
Yarn upgrades to 2.4; sass replaces node-sass.

### PR DESCRIPTION
**Pull request by sandroroux**
[`node-sass` is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and the older version of yarn 2 threw `fsevents` errors.

### CODE REVIEW

**Comment by PeteCoward** [comment]
superceded in #379 , will close tomorrow.

**Comment by md8n** [comment]
Not completely superseded there's still the issue of node-sass to get rid of

**Comment by PeteCoward** [comment]
This is on hold for now, until we work out how best to merge it

**Comment by PeteCoward** [comment]
@sandroroux can we close this in favour of #492 which makes the same node-sass to sass change?

**Comment by sandroroux** [comment]
Closing this in favor of #492.

**Pull request closed without merging**
